#[derive(Debug)]
pub struct YscScriptHeader {
  pub magic:                u32,
  pub sub_header:           u32,
  pub code_blocks_offset:   u32,
  pub globals_version:      u32,
  pub code_size:            u32,
  pub parameter_count:      u32,
  pub statics_count:        u32,
  pub globals_count:        u32,
  pub natives_count:        u32,
  pub statics_offset:       u32,
  pub globals_offset:       u32,
  pub natives_offset:       u32,
  pub name_hash:            u32,
  pub script_name_offset:   u32,
  pub string_offset:        u32,
  pub strings_size:         u32,
  pub rsc7_offset:          Option<u32>,
  pub string_table_offsets: Vec<u32>,
  pub code_table_offsets:   Vec<u32>,
  pub string_blocks:        u32,
  pub code_blocks:          u32,
  pub script_name:          String
}
