[package]
name = "gta5-script-decompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary-layout = "3.0.0"
binary-reader = "0.4.5"
thiserror = "1.0.31"
