[package]
name = "gta5-script-decompiler"
version = "0.1.0"
edition = "2021"

[lib]
name = "gta5_script_decompiler"
path = "src/lib.rs"

[dependencies]
binary-layout = "3.0.0"
binary-reader = "0.4.5"
thiserror = "1.0.31"
num_enum = "0.6.1"
anyhow = "1.0.68"
